services:
  node_service:
    image: node_image
    ports:
      - "3000:3000"
    depends_on:
      - db_service
      
  db_service:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /service_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_node

